language: erlang
script: "make compile && make test"
notifications:
  hipchat:
  	- secure: "Eq98Rr2ggMItuedgcnGlNVzXO7ZDDyEFawdDG5CviIOQVRGeq0dsKYEK7Tmn\nMDFJyYRDZ9s+oXOQYkx796Sn1Qtlthy416hH4ymCCexRg5mLoE3/5P89O2Wr\n9mMQPieV2pmIOplPrwKEWTYTS5OyrjOJW+uWgOVi6gf8iWHsCFk="
otp_release:
  - R15B02
  - R15B01
  - R15B
  - R14B04
  - R14B03
  - R14B02