language: erlang
notifications:
  hipchat:
    - secure: "kTli2lyPoRjPOn1Ku39Oa+Mv2Tf/0gOei2mJkZfdHdZpcGH1nzoKmUe1Nhwk\nkzMB2XmgwF6PHm3nKpMuU72V6aWDoTEUASIgyqLRsZmqMWBs8pg3BvPg0NbR\nlm7tx4AVLq7CyESJV6XWqdhTAsQnNBCybBnbrtaWtV8jmUI2/HQ="
otp_release:
  - 18.2.1
  - 18.2
  - 18.1
  - 18.0
  - 17.5
  - 17.4
  - 17.3
  - 17.1
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R15B03
  - R15B02
  - R15B01
  - R15B
script: "make test"
